spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
      open-in-view : false

jwt:
  secret:
    key: ${JWT_SECRET_KEY}


file:
  upload-dir: "C:/Sparta_camp/First_Spring/Spring_Plus/src/main/java/com/example/spring_plus/file/images/"
